import { Tournament } from "@kakomimasu/client-js";

export const tournamentDummyData = (id: number): Tournament => {
  return {
    id: id.toString(),
    name: `ここはname ${id}`,
    organizer: `ここはorganizer ${id}`,
    type: "round-robin",
    remarks: `ここはremarks ${id}`,
    users: [],
    gameIds: [],
  };
};

export const gameDummySSEData = {
  type: "initial",
  q: "sort:startAtUnixTime-desc type:normal",
  endIndex: 1,
  games: [
    {
      totalTurn: 60,
      log: [
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 128 },
              actions: [
                { agentId: 0, type: 1, x: 19, y: 0, res: 0 },
                { agentId: 1, type: 1, x: 8, y: 1, res: 0 },
                { agentId: 2, type: 1, x: 2, y: 3, res: 0 },
                { agentId: 3, type: 1, x: 12, y: 3, res: 0 },
                { agentId: 4, type: 1, x: 18, y: 3, res: 0 },
                { agentId: 5, type: 1, x: 19, y: 3, res: 0 },
                { agentId: 6, type: 1, x: 1, y: 4, res: 0 },
                { agentId: 7, type: 1, x: 7, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 105 },
              actions: [
                { agentId: 0, type: 3, x: 20, y: 1, res: 5 },
                { agentId: 1, type: 3, x: 7, y: 1, res: 0 },
                { agentId: 2, type: 3, x: 3, y: 3, res: 0 },
                { agentId: 3, type: 3, x: 13, y: 2, res: 0 },
                { agentId: 4, type: 3, x: 18, y: 2, res: 0 },
                { agentId: 5, type: 3, x: 18, y: 3, res: 0 },
                { agentId: 6, type: 3, x: 1, y: 5, res: 0 },
                { agentId: 7, type: 3, x: 8, y: 3, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 64 },
              actions: [
                { agentId: 0, type: 3, x: 19, y: 1, res: 1 },
                { agentId: 1, type: 3, x: 6, y: 1, res: 0 },
                { agentId: 2, type: 3, x: 2, y: 2, res: 0 },
                { agentId: 3, type: 3, x: 12, y: 2, res: 0 },
                { agentId: 4, type: 3, x: 19, y: 1, res: 1 },
                { agentId: 5, type: 3, x: 18, y: 2, res: 2 },
                { agentId: 6, type: 3, x: 1, y: 6, res: 0 },
                { agentId: 7, type: 3, x: 9, y: 3, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 71 },
              actions: [
                { agentId: 0, type: 3, x: 20, y: 1, res: 5 },
                { agentId: 1, type: 3, x: 7, y: 1, res: 0 },
                { agentId: 2, type: 3, x: 3, y: 2, res: 0 },
                { agentId: 3, type: 3, x: 12, y: 3, res: 0 },
                { agentId: 4, type: 3, x: 17, y: 2, res: 0 },
                { agentId: 5, type: 3, x: 17, y: 4, res: 0 },
                { agentId: 6, type: 3, x: 1, y: 5, res: 0 },
                { agentId: 7, type: 3, x: 9, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 80 },
              actions: [
                { agentId: 0, type: 3, x: 20, y: 1, res: 5 },
                { agentId: 1, type: 3, x: 6, y: 1, res: 0 },
                { agentId: 2, type: 3, x: 2, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 13, y: 3, res: 0 },
                { agentId: 4, type: 3, x: 16, y: 3, res: 0 },
                { agentId: 5, type: 3, x: 16, y: 5, res: 0 },
                { agentId: 6, type: 3, x: 1, y: 6, res: 0 },
                { agentId: 7, type: 3, x: 8, y: 5, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 110 },
              actions: [
                { agentId: 0, type: 3, x: 19, y: -1, res: 5 },
                { agentId: 1, type: 3, x: 7, y: 2, res: 0 },
                { agentId: 2, type: 3, x: 3, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 12, y: 3, res: 0 },
                { agentId: 4, type: 3, x: 17, y: 4, res: 0 },
                { agentId: 5, type: 3, x: 15, y: 5, res: 0 },
                { agentId: 6, type: 3, x: 2, y: 7, res: 0 },
                { agentId: 7, type: 3, x: 9, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 124 },
              actions: [
                { agentId: 0, type: 3, x: 18, y: 1, res: 0 },
                { agentId: 1, type: 3, x: 6, y: 3, res: 0 },
                { agentId: 2, type: 3, x: 2, y: 0, res: 0 },
                { agentId: 3, type: 3, x: 11, y: 4, res: 0 },
                { agentId: 4, type: 3, x: 18, y: 5, res: 0 },
                { agentId: 5, type: 3, x: 16, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 3, y: 7, res: 0 },
                { agentId: 7, type: 3, x: 10, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 116 },
              actions: [
                { agentId: 0, type: 3, x: 17, y: 0, res: 0 },
                { agentId: 1, type: 3, x: 6, y: 2, res: 0 },
                { agentId: 2, type: 3, x: 1, y: -1, res: 5 },
                { agentId: 3, type: 3, x: 11, y: 5, res: 0 },
                { agentId: 4, type: 3, x: 18, y: 6, res: 0 },
                { agentId: 5, type: 3, x: 15, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 2, y: 8, res: 0 },
                { agentId: 7, type: 3, x: 9, y: 5, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 145 },
              actions: [
                { agentId: 0, type: 3, x: 16, y: 0, res: 0 },
                { agentId: 1, type: 3, x: 7, y: 1, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 0, res: 0 },
                { agentId: 3, type: 3, x: 12, y: 6, res: 0 },
                { agentId: 4, type: 3, x: 18, y: 5, res: 0 },
                { agentId: 5, type: 3, x: 14, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 3, y: 9, res: 0 },
                { agentId: 7, type: 3, x: 8, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 177 },
              actions: [
                { agentId: 0, type: 3, x: 15, y: 0, res: 0 },
                { agentId: 1, type: 3, x: 7, y: 0, res: 0 },
                { agentId: 2, type: 3, x: 2, y: -1, res: 5 },
                { agentId: 3, type: 3, x: 13, y: 7, res: 0 },
                { agentId: 4, type: 3, x: 17, y: 4, res: 0 },
                { agentId: 5, type: 3, x: 15, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 4, y: 10, res: 0 },
                { agentId: 7, type: 3, x: 9, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 203 },
              actions: [
                { agentId: 0, type: 3, x: 14, y: 1, res: 0 },
                { agentId: 1, type: 3, x: 8, y: 1, res: 0 },
                { agentId: 2, type: 3, x: 0, y: 0, res: 0 },
                { agentId: 3, type: 3, x: 12, y: 7, res: 0 },
                { agentId: 4, type: 3, x: 16, y: 4, res: 0 },
                { agentId: 5, type: 3, x: 16, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 3, y: 11, res: 0 },
                { agentId: 7, type: 3, x: 10, y: 3, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 220 },
              actions: [
                { agentId: 0, type: 3, x: 13, y: 1, res: 0 },
                { agentId: 1, type: 3, x: 9, y: 0, res: 0 },
                { agentId: 2, type: 3, x: 0, y: -1, res: 5 },
                { agentId: 3, type: 3, x: 13, y: 7, res: 0 },
                { agentId: 4, type: 3, x: 17, y: 3, res: 0 },
                { agentId: 5, type: 3, x: 17, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 3, y: 12, res: 0 },
                { agentId: 7, type: 3, x: 11, y: 2, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 218 },
              actions: [
                { agentId: 0, type: 3, x: 12, y: 2, res: 0 },
                { agentId: 1, type: 3, x: 10, y: 0, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 14, y: 8, res: 0 },
                { agentId: 4, type: 3, x: 16, y: 3, res: 0 },
                { agentId: 5, type: 3, x: 18, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 2, y: 11, res: 0 },
                { agentId: 7, type: 3, x: 10, y: 1, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 220 },
              actions: [
                { agentId: 0, type: 3, x: 12, y: 1, res: 0 },
                { agentId: 1, type: 3, x: 10, y: 1, res: 0 },
                { agentId: 2, type: 3, x: 0, y: 0, res: 0 },
                { agentId: 3, type: 3, x: 13, y: 8, res: 0 },
                { agentId: 4, type: 3, x: 17, y: 2, res: 0 },
                { agentId: 5, type: 3, x: 17, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 2, y: 10, res: 0 },
                { agentId: 7, type: 3, x: 9, y: 0, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 244 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 0, res: 0 },
                { agentId: 1, type: 3, x: 11, y: 2, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 13, y: 9, res: 0 },
                { agentId: 4, type: 3, x: 16, y: 3, res: 0 },
                { agentId: 5, type: 3, x: 17, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 1, y: 11, res: 0 },
                { agentId: 7, type: 3, x: 8, y: 1, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 255 },
              actions: [
                { agentId: 0, type: 3, x: 10, y: 0, res: 0 },
                { agentId: 1, type: 3, x: 10, y: 1, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 0, res: 0 },
                { agentId: 3, type: 3, x: 12, y: 9, res: 0 },
                { agentId: 4, type: 3, x: 15, y: 2, res: 0 },
                { agentId: 5, type: 3, x: 17, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 0, y: 10, res: 0 },
                { agentId: 7, type: 3, x: 9, y: 1, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 246 },
              actions: [
                { agentId: 0, type: 3, x: 10, y: 1, res: 0 },
                { agentId: 1, type: 3, x: 9, y: 0, res: 0 },
                { agentId: 2, type: 3, x: 0, y: 0, res: 0 },
                { agentId: 3, type: 3, x: 11, y: 9, res: 0 },
                { agentId: 4, type: 3, x: 14, y: 3, res: 0 },
                { agentId: 5, type: 3, x: 16, y: 5, res: 0 },
                { agentId: 6, type: 3, x: 1, y: 10, res: 0 },
                { agentId: 7, type: 3, x: 8, y: 1, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 231 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 2, res: 0 },
                { agentId: 1, type: 3, x: 8, y: -1, res: 5 },
                { agentId: 2, type: 3, x: 1, y: 0, res: 0 },
                { agentId: 3, type: 3, x: 10, y: 10, res: 0 },
                { agentId: 4, type: 3, x: 14, y: 4, res: 0 },
                { agentId: 5, type: 3, x: 17, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 1, y: 11, res: 0 },
                { agentId: 7, type: 3, x: 9, y: 0, res: 2 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 239 },
              actions: [
                { agentId: 0, type: 3, x: 10, y: 1, res: 0 },
                { agentId: 1, type: 3, x: 8, y: -1, res: 5 },
                { agentId: 2, type: 3, x: 0, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 11, y: 10, res: 0 },
                { agentId: 4, type: 3, x: 14, y: 5, res: 0 },
                { agentId: 5, type: 3, x: 18, y: 5, res: 0 },
                { agentId: 6, type: 3, x: 0, y: 12, res: 0 },
                { agentId: 7, type: 3, x: 7, y: 0, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 223 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 2, res: 0 },
                { agentId: 1, type: 3, x: 8, y: 1, res: 0 },
                { agentId: 2, type: 3, x: 0, y: 0, res: 0 },
                { agentId: 3, type: 3, x: 10, y: 10, res: 0 },
                { agentId: 4, type: 3, x: 13, y: 5, res: 0 },
                { agentId: 5, type: 3, x: 18, y: 6, res: 0 },
                { agentId: 6, type: 3, x: -1, y: 11, res: 5 },
                { agentId: 7, type: 3, x: 7, y: -1, res: 5 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 199 },
              actions: [
                { agentId: 0, type: 3, x: 10, y: 1, res: 0 },
                { agentId: 1, type: 3, x: 9, y: 1, res: 0 },
                { agentId: 2, type: 3, x: -1, y: 0, res: 5 },
                { agentId: 3, type: 3, x: 9, y: 10, res: 0 },
                { agentId: 4, type: 3, x: 13, y: 4, res: 0 },
                { agentId: 5, type: 3, x: 17, y: 5, res: 0 },
                { agentId: 6, type: 3, x: -1, y: 11, res: 5 },
                { agentId: 7, type: 3, x: 8, y: 1, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 228 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 2, res: 0 },
                { agentId: 1, type: 3, x: 8, y: 0, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 0, res: 0 },
                { agentId: 3, type: 3, x: 8, y: 11, res: 0 },
                { agentId: 4, type: 3, x: 13, y: 5, res: 0 },
                { agentId: 5, type: 3, x: 16, y: 4, res: 0 },
                { agentId: 6, type: 3, x: 0, y: 11, res: 0 },
                { agentId: 7, type: 3, x: 7, y: 2, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 255 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 1, res: 0 },
                { agentId: 1, type: 3, x: 9, y: -1, res: 5 },
                { agentId: 2, type: 3, x: 0, y: -1, res: 5 },
                { agentId: 3, type: 3, x: 8, y: 10, res: 0 },
                { agentId: 4, type: 3, x: 14, y: 6, res: 0 },
                { agentId: 5, type: 3, x: 16, y: 5, res: 0 },
                { agentId: 6, type: 3, x: 1, y: 12, res: 0 },
                { agentId: 7, type: 3, x: 7, y: 1, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 266 },
              actions: [
                { agentId: 0, type: 3, x: 12, y: 0, res: 0 },
                { agentId: 1, type: 3, x: 7, y: 1, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 8, y: 9, res: 0 },
                { agentId: 4, type: 3, x: 15, y: 6, res: 0 },
                { agentId: 5, type: 3, x: 15, y: 4, res: 0 },
                { agentId: 6, type: 3, x: 2, y: 13, res: 0 },
                { agentId: 7, type: 3, x: 8, y: 1, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 251 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: -1, res: 5 },
                { agentId: 1, type: 3, x: 6, y: 1, res: 0 },
                { agentId: 2, type: 3, x: 2, y: 0, res: 0 },
                { agentId: 3, type: 3, x: 8, y: 10, res: 0 },
                { agentId: 4, type: 3, x: 16, y: 5, res: 0 },
                { agentId: 5, type: 3, x: 14, y: 4, res: 0 },
                { agentId: 6, type: 3, x: 1, y: 13, res: 0 },
                { agentId: 7, type: 3, x: 8, y: 2, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 267 },
              actions: [
                { agentId: 0, type: 3, x: 12, y: 1, res: 0 },
                { agentId: 1, type: 3, x: 7, y: 2, res: 0 },
                { agentId: 2, type: 3, x: 2, y: -1, res: 5 },
                { agentId: 3, type: 3, x: 9, y: 10, res: 0 },
                { agentId: 4, type: 3, x: 16, y: 4, res: 0 },
                { agentId: 5, type: 3, x: 13, y: 5, res: 0 },
                { agentId: 6, type: 3, x: 0, y: 14, res: 0 },
                { agentId: 7, type: 3, x: 7, y: 3, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 47, wallPoint: 275 },
              actions: [
                { agentId: 0, type: 3, x: 12, y: 2, res: 0 },
                { agentId: 1, type: 3, x: 6, y: 3, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 10, y: 11, res: 0 },
                { agentId: 4, type: 3, x: 16, y: 5, res: 0 },
                { agentId: 5, type: 3, x: 12, y: 5, res: 0 },
                { agentId: 6, type: 3, x: -1, y: 13, res: 5 },
                { agentId: 7, type: 3, x: 8, y: 3, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 47, wallPoint: 312 },
              actions: [
                { agentId: 0, type: 3, x: 12, y: 1, res: 0 },
                { agentId: 1, type: 3, x: 6, y: 4, res: 0 },
                { agentId: 2, type: 3, x: 0, y: 0, res: 0 },
                { agentId: 3, type: 3, x: 9, y: 11, res: 0 },
                { agentId: 4, type: 3, x: 15, y: 4, res: 0 },
                { agentId: 5, type: 3, x: 11, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 1, y: 15, res: 0 },
                { agentId: 7, type: 3, x: 7, y: 3, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 47, wallPoint: 325 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 1, res: 0 },
                { agentId: 1, type: 3, x: 7, y: 5, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 9, y: 10, res: 0 },
                { agentId: 4, type: 3, x: 15, y: 5, res: 0 },
                { agentId: 5, type: 3, x: 10, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 0, y: 15, res: 0 },
                { agentId: 7, type: 3, x: 7, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 47, wallPoint: 312 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 0, res: 0 },
                { agentId: 1, type: 3, x: 8, y: 5, res: 0 },
                { agentId: 2, type: 3, x: 2, y: 2, res: 0 },
                { agentId: 3, type: 3, x: 8, y: 10, res: 0 },
                { agentId: 4, type: 3, x: 14, y: 4, res: 0 },
                { agentId: 5, type: 3, x: 11, y: 8, res: 0 },
                { agentId: 6, type: 3, x: 1, y: 14, res: 0 },
                { agentId: 7, type: 3, x: 8, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 47, wallPoint: 312 },
              actions: [
                { agentId: 0, type: 3, x: 12, y: 0, res: 0 },
                { agentId: 1, type: 3, x: 7, y: 4, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 9, y: 11, res: 0 },
                { agentId: 4, type: 3, x: 14, y: 3, res: 0 },
                { agentId: 5, type: 3, x: 10, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 2, y: 13, res: 0 },
                { agentId: 7, type: 3, x: 9, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 56, wallPoint: 291 },
              actions: [
                { agentId: 0, type: 3, x: 13, y: 1, res: 0 },
                { agentId: 1, type: 3, x: 8, y: 4, res: 0 },
                { agentId: 2, type: 3, x: 0, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 10, y: 10, res: 0 },
                { agentId: 4, type: 3, x: 14, y: 2, res: 0 },
                { agentId: 5, type: 3, x: 11, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 2, y: 14, res: 0 },
                { agentId: 7, type: 3, x: 8, y: 3, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 31, wallPoint: 287 },
              actions: [
                { agentId: 0, type: 3, x: 14, y: 1, res: 0 },
                { agentId: 1, type: 3, x: 9, y: 3, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 11, y: 9, res: 0 },
                { agentId: 4, type: 3, x: 15, y: 1, res: 0 },
                { agentId: 5, type: 3, x: 12, y: 8, res: 0 },
                { agentId: 6, type: 3, x: 2, y: 13, res: 0 },
                { agentId: 7, type: 3, x: 9, y: 2, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 32, wallPoint: 306 },
              actions: [
                { agentId: 0, type: 3, x: 13, y: 1, res: 0 },
                { agentId: 1, type: 3, x: 9, y: 4, res: 0 },
                { agentId: 2, type: 3, x: 2, y: 0, res: 0 },
                { agentId: 3, type: 3, x: 12, y: 8, res: 0 },
                { agentId: 4, type: 3, x: 16, y: 2, res: 0 },
                { agentId: 5, type: 3, x: 13, y: 8, res: 0 },
                { agentId: 6, type: 3, x: 3, y: 14, res: 0 },
                { agentId: 7, type: 3, x: 10, y: 3, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 32, wallPoint: 292 },
              actions: [
                { agentId: 0, type: 3, x: 13, y: 2, res: 0 },
                { agentId: 1, type: 3, x: 9, y: 3, res: 0 },
                { agentId: 2, type: 3, x: 1, y: -1, res: 5 },
                { agentId: 3, type: 3, x: 11, y: 8, res: 0 },
                { agentId: 4, type: 3, x: 17, y: 3, res: 0 },
                { agentId: 5, type: 3, x: 14, y: 9, res: 0 },
                { agentId: 6, type: 3, x: 4, y: 15, res: 0 },
                { agentId: 7, type: 3, x: 11, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 64, wallPoint: 296 },
              actions: [
                { agentId: 0, type: 3, x: 12, y: 2, res: 0 },
                { agentId: 1, type: 3, x: 10, y: 4, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 11, y: 7, res: 0 },
                { agentId: 4, type: 3, x: 16, y: 4, res: 0 },
                { agentId: 5, type: 3, x: 15, y: 8, res: 0 },
                { agentId: 6, type: 3, x: 4, y: 14, res: 0 },
                { agentId: 7, type: 3, x: 10, y: 5, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 53, wallPoint: 260 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 3, res: 0 },
                { agentId: 1, type: 3, x: 10, y: 3, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 2, res: 0 },
                { agentId: 3, type: 3, x: 10, y: 6, res: 0 },
                { agentId: 4, type: 3, x: 16, y: 3, res: 0 },
                { agentId: 5, type: 3, x: 16, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 5, y: 13, res: 0 },
                { agentId: 7, type: 3, x: 11, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 49, wallPoint: 281 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 4, res: 0 },
                { agentId: 1, type: 3, x: 11, y: 3, res: 0 },
                { agentId: 2, type: 3, x: 0, y: 2, res: 0 },
                { agentId: 3, type: 3, x: 10, y: 5, res: 0 },
                { agentId: 4, type: 3, x: 17, y: 2, res: 0 },
                { agentId: 5, type: 3, x: 17, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 5, y: 12, res: 0 },
                { agentId: 7, type: 3, x: 12, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 49, wallPoint: 293 },
              actions: [
                { agentId: 0, type: 3, x: 10, y: 5, res: 0 },
                { agentId: 1, type: 3, x: 12, y: 4, res: 0 },
                { agentId: 2, type: 3, x: -1, y: 2, res: 5 },
                { agentId: 3, type: 3, x: 9, y: 5, res: 0 },
                { agentId: 4, type: 3, x: 18, y: 2, res: 0 },
                { agentId: 5, type: 3, x: 18, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 6, y: 11, res: 0 },
                { agentId: 7, type: 3, x: 13, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 49, wallPoint: 287 },
              actions: [
                { agentId: 0, type: 3, x: 10, y: 4, res: 0 },
                { agentId: 1, type: 3, x: 11, y: 5, res: 0 },
                { agentId: 2, type: 3, x: 0, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 9, y: 4, res: 0 },
                { agentId: 4, type: 3, x: 19, y: 2, res: 0 },
                { agentId: 5, type: 3, x: 17, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 5, y: 10, res: 0 },
                { agentId: 7, type: 3, x: 12, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 49, wallPoint: 297 },
              actions: [
                { agentId: 0, type: 3, x: 10, y: 5, res: 0 },
                { agentId: 1, type: 3, x: 12, y: 4, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 9, y: 3, res: 0 },
                { agentId: 4, type: 3, x: 19, y: 3, res: 0 },
                { agentId: 5, type: 3, x: 18, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 4, y: 9, res: 0 },
                { agentId: 7, type: 3, x: 11, y: 5, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 49, wallPoint: 308 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 5, res: 0 },
                { agentId: 1, type: 3, x: 11, y: 4, res: 0 },
                { agentId: 2, type: 3, x: 0, y: 2, res: 0 },
                { agentId: 3, type: 3, x: 10, y: 4, res: 0 },
                { agentId: 4, type: 3, x: 18, y: 2, res: 0 },
                { agentId: 5, type: 3, x: 17, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 3, y: 8, res: 0 },
                { agentId: 7, type: 3, x: 11, y: 6, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 49, wallPoint: 320 },
              actions: [
                { agentId: 0, type: 3, x: 12, y: 4, res: 0 },
                { agentId: 1, type: 3, x: 12, y: 3, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 11, y: 3, res: 0 },
                { agentId: 4, type: 3, x: 17, y: 2, res: 0 },
                { agentId: 5, type: 3, x: 17, y: 8, res: 0 },
                { agentId: 6, type: 3, x: 3, y: 9, res: 0 },
                { agentId: 7, type: 3, x: 11, y: 5, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 49, wallPoint: 320 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 4, res: 1 },
                { agentId: 1, type: 3, x: 11, y: 4, res: 1 },
                { agentId: 2, type: 3, x: 1, y: 2, res: 0 },
                { agentId: 3, type: 3, x: 11, y: 2, res: 0 },
                { agentId: 4, type: 3, x: 16, y: 3, res: 0 },
                { agentId: 5, type: 3, x: 16, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 4, y: 10, res: 0 },
                { agentId: 7, type: 3, x: 11, y: 6, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 49, wallPoint: 320 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 4, res: 0 },
                { agentId: 1, type: 3, x: 12, y: 2, res: 1 },
                { agentId: 2, type: 3, x: 2, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 12, y: 2, res: 1 },
                { agentId: 4, type: 3, x: 15, y: 4, res: 0 },
                { agentId: 5, type: 3, x: 15, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 4, y: 9, res: 0 },
                { agentId: 7, type: 3, x: 12, y: 6, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 49, wallPoint: 320 },
              actions: [
                { agentId: 0, type: 3, x: 12, y: 3, res: 0 },
                { agentId: 1, type: 3, x: 13, y: 3, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 0, res: 0 },
                { agentId: 3, type: 3, x: 12, y: 1, res: 0 },
                { agentId: 4, type: 3, x: 14, y: 4, res: 0 },
                { agentId: 5, type: 3, x: 14, y: 8, res: 0 },
                { agentId: 6, type: 3, x: 3, y: 9, res: 0 },
                { agentId: 7, type: 3, x: 11, y: 6, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 49, wallPoint: 327 },
              actions: [
                { agentId: 0, type: 3, x: 13, y: 4, res: 0 },
                { agentId: 1, type: 3, x: 12, y: 4, res: 0 },
                { agentId: 2, type: 3, x: 0, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 13, y: 2, res: 0 },
                { agentId: 4, type: 3, x: 13, y: 5, res: 0 },
                { agentId: 5, type: 3, x: 15, y: 8, res: 0 },
                { agentId: 6, type: 3, x: 3, y: 10, res: 0 },
                { agentId: 7, type: 3, x: 12, y: 5, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 49, wallPoint: 311 },
              actions: [
                { agentId: 0, type: 3, x: 12, y: 4, res: 0 },
                { agentId: 1, type: 3, x: 13, y: 3, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 14, y: 3, res: 0 },
                { agentId: 4, type: 3, x: 14, y: 6, res: 0 },
                { agentId: 5, type: 3, x: 14, y: 9, res: 0 },
                { agentId: 6, type: 3, x: 2, y: 9, res: 0 },
                { agentId: 7, type: 3, x: 13, y: 5, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 49, wallPoint: 321 },
              actions: [
                { agentId: 0, type: 3, x: 13, y: 5, res: 0 },
                { agentId: 1, type: 3, x: 12, y: 4, res: 0 },
                { agentId: 2, type: 3, x: 0, y: 0, res: 0 },
                { agentId: 3, type: 3, x: 13, y: 3, res: 0 },
                { agentId: 4, type: 3, x: 14, y: 5, res: 0 },
                { agentId: 5, type: 3, x: 15, y: 9, res: 0 },
                { agentId: 6, type: 3, x: 3, y: 10, res: 0 },
                { agentId: 7, type: 3, x: 14, y: 4, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 33, wallPoint: 305 },
              actions: [
                { agentId: 0, type: 3, x: 13, y: 6, res: 0 },
                { agentId: 1, type: 3, x: 12, y: 3, res: 0 },
                { agentId: 2, type: 3, x: -1, y: 1, res: 5 },
                { agentId: 3, type: 3, x: 14, y: 2, res: 0 },
                { agentId: 4, type: 3, x: 13, y: 4, res: 0 },
                { agentId: 5, type: 3, x: 15, y: 8, res: 0 },
                { agentId: 6, type: 3, x: 2, y: 10, res: 0 },
                { agentId: 7, type: 3, x: 14, y: 5, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 16, wallPoint: 314 },
              actions: [
                { agentId: 0, type: 3, x: 14, y: 7, res: 0 },
                { agentId: 1, type: 3, x: 11, y: 3, res: 0 },
                { agentId: 2, type: 3, x: -1, y: -1, res: 5 },
                { agentId: 3, type: 3, x: 15, y: 3, res: 0 },
                { agentId: 4, type: 3, x: 14, y: 4, res: 0 },
                { agentId: 5, type: 3, x: 16, y: 8, res: 0 },
                { agentId: 6, type: 3, x: 1, y: 9, res: 0 },
                { agentId: 7, type: 3, x: 15, y: 6, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 16, wallPoint: 320 },
              actions: [
                { agentId: 0, type: 3, x: 13, y: 7, res: 0 },
                { agentId: 1, type: 3, x: 11, y: 2, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 16, y: 2, res: 0 },
                { agentId: 4, type: 3, x: 14, y: 5, res: 0 },
                { agentId: 5, type: 3, x: 17, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 0, y: 9, res: 0 },
                { agentId: 7, type: 3, x: 15, y: 7, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 16, wallPoint: 329 },
              actions: [
                { agentId: 0, type: 3, x: 12, y: 7, res: 0 },
                { agentId: 1, type: 3, x: 11, y: 3, res: 0 },
                { agentId: 2, type: 3, x: 2, y: 2, res: 0 },
                { agentId: 3, type: 3, x: 15, y: 1, res: 0 },
                { agentId: 4, type: 3, x: 14, y: 6, res: 0 },
                { agentId: 5, type: 3, x: 18, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 0, y: 8, res: 0 },
                { agentId: 7, type: 3, x: 14, y: 8, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 16, wallPoint: 340 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 6, res: 0 },
                { agentId: 1, type: 3, x: 12, y: 2, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 1, res: 0 },
                { agentId: 3, type: 3, x: 15, y: 2, res: 0 },
                { agentId: 4, type: 3, x: 14, y: 7, res: 0 },
                { agentId: 5, type: 3, x: 19, y: 6, res: 0 },
                { agentId: 6, type: 3, x: -1, y: 7, res: 5 },
                { agentId: 7, type: 3, x: 15, y: 7, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 16, wallPoint: 352 },
              actions: [
                { agentId: 0, type: 3, x: 10, y: 5, res: 0 },
                { agentId: 1, type: 3, x: 11, y: 1, res: 0 },
                { agentId: 2, type: 3, x: 0, y: 2, res: 0 },
                { agentId: 3, type: 3, x: 14, y: 2, res: 0 },
                { agentId: 4, type: 3, x: 13, y: 7, res: 0 },
                { agentId: 5, type: 3, x: 18, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 1, y: 8, res: 0 },
                { agentId: 7, type: 3, x: 15, y: 6, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 16, wallPoint: 364 },
              actions: [
                { agentId: 0, type: 3, x: 10, y: 6, res: 0 },
                { agentId: 1, type: 3, x: 12, y: 2, res: 0 },
                { agentId: 2, type: 3, x: 1, y: 3, res: 0 },
                { agentId: 3, type: 3, x: 13, y: 3, res: 0 },
                { agentId: 4, type: 3, x: 13, y: 8, res: 0 },
                { agentId: 5, type: 3, x: 19, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 0, y: 8, res: 0 },
                { agentId: 7, type: 3, x: 14, y: 7, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 16, wallPoint: 365 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 6, res: 0 },
                { agentId: 1, type: 3, x: 11, y: 2, res: 0 },
                { agentId: 2, type: 3, x: 2, y: 4, res: 0 },
                { agentId: 3, type: 3, x: 13, y: 4, res: 0 },
                { agentId: 4, type: 3, x: 13, y: 9, res: 0 },
                { agentId: 5, type: 3, x: 18, y: 5, res: 0 },
                { agentId: 6, type: 3, x: 0, y: 9, res: 0 },
                { agentId: 7, type: 3, x: 15, y: 8, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 360 },
              actions: [
                { agentId: 0, type: 3, x: 11, y: 7, res: 0 },
                { agentId: 1, type: 3, x: 10, y: 2, res: 0 },
                { agentId: 2, type: 3, x: 3, y: 5, res: 0 },
                { agentId: 3, type: 3, x: 13, y: 3, res: 0 },
                { agentId: 4, type: 3, x: 12, y: 8, res: 0 },
                { agentId: 5, type: 3, x: 17, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 1, y: 8, res: 0 },
                { agentId: 7, type: 3, x: 16, y: 7, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 376 },
              actions: [
                { agentId: 0, type: 3, x: 10, y: 6, res: 0 },
                { agentId: 1, type: 3, x: 11, y: 2, res: 0 },
                { agentId: 2, type: 3, x: 4, y: 4, res: 0 },
                { agentId: 3, type: 3, x: 14, y: 4, res: 0 },
                { agentId: 4, type: 3, x: 11, y: 8, res: 0 },
                { agentId: 5, type: 3, x: 16, y: 6, res: 0 },
                { agentId: 6, type: 3, x: 0, y: 7, res: 0 },
                { agentId: 7, type: 3, x: 17, y: 8, res: 0 },
              ],
            },
          ],
        },
        {
          players: [
            { point: { areaPoint: 0, wallPoint: 0 }, actions: [] },
            {
              point: { areaPoint: 0, wallPoint: 363 },
              actions: [
                { agentId: 0, type: 3, x: 10, y: 5, res: 0 },
                { agentId: 1, type: 3, x: 12, y: 1, res: 0 },
                { agentId: 2, type: 3, x: 5, y: 5, res: 0 },
                { agentId: 3, type: 3, x: 15, y: 5, res: 0 },
                { agentId: 4, type: 3, x: 12, y: 9, res: 0 },
                { agentId: 5, type: 3, x: 16, y: 7, res: 0 },
                { agentId: 6, type: 3, x: 1, y: 8, res: 0 },
                { agentId: 7, type: 3, x: 16, y: 9, res: 0 },
              ],
            },
          ],
        },
      ],
      turn: 60,
      id: "b3b85f61-2678-4744-938e-ca376e8d4e17",
      name: "対AI戦：ゲスト vs AI(a1)",
      startedAtUnixTime: 1713356051,
      reservedUsers: [],
      type: "normal",
      ai: {
        playerIndex: 1,
        pntall: [
          { x: 13, y: 0, point: 16 },
          { x: 19, y: 0, point: 16 },
          { x: 8, y: 1, point: 16 },
          { x: 2, y: 3, point: 16 },
          { x: 12, y: 3, point: 16 },
          { x: 18, y: 3, point: 16 },
          { x: 19, y: 3, point: 16 },
          { x: 1, y: 4, point: 16 },
          { x: 7, y: 4, point: 16 },
          { x: 15, y: 6, point: 16 },
          { x: 6, y: 7, point: 16 },
          { x: 14, y: 7, point: 16 },
          { x: 17, y: 7, point: 16 },
          { x: 19, y: 7, point: 16 },
          { x: 15, y: 11, point: 16 },
          { x: 18, y: 12, point: 16 },
          { x: 16, y: 14, point: 16 },
          { x: 10, y: 15, point: 16 },
          { x: 12, y: 17, point: 16 },
          { x: 16, y: 18, point: 16 },
          { x: 18, y: 19, point: 16 },
          { x: 1, y: 0, point: 15 },
          { x: 4, y: 0, point: 15 },
          { x: 9, y: 0, point: 15 },
          { x: 11, y: 0, point: 15 },
          { x: 0, y: 2, point: 15 },
          { x: 16, y: 2, point: 15 },
          { x: 7, y: 3, point: 15 },
          { x: 3, y: 4, point: 15 },
          { x: 0, y: 6, point: 15 },
          { x: 2, y: 7, point: 15 },
          { x: 15, y: 8, point: 15 },
          { x: 18, y: 8, point: 15 },
          { x: 7, y: 10, point: 15 },
          { x: 3, y: 11, point: 15 },
          { x: 9, y: 12, point: 15 },
          { x: 10, y: 12, point: 15 },
          { x: 11, y: 13, point: 15 },
          { x: 11, y: 15, point: 15 },
          { x: 13, y: 15, point: 15 },
          { x: 3, y: 17, point: 15 },
          { x: 6, y: 0, point: 14 },
          { x: 0, y: 1, point: 14 },
          { x: 4, y: 1, point: 14 },
          { x: 11, y: 1, point: 14 },
          { x: 11, y: 2, point: 14 },
          { x: 16, y: 3, point: 14 },
          { x: 9, y: 4, point: 14 },
          { x: 18, y: 4, point: 14 },
          { x: 11, y: 5, point: 14 },
          { x: 9, y: 7, point: 14 },
          { x: 14, y: 8, point: 14 },
          { x: 12, y: 9, point: 14 },
          { x: 5, y: 11, point: 14 },
          { x: 4, y: 12, point: 14 },
          { x: 15, y: 13, point: 14 },
          { x: 4, y: 16, point: 14 },
          { x: 5, y: 16, point: 14 },
          { x: 19, y: 17, point: 14 },
          { x: 3, y: 19, point: 14 },
          { x: 17, y: 19, point: 14 },
          { x: 14, y: 0, point: 13 },
          { x: 1, y: 7, point: 13 },
          { x: 8, y: 9, point: 13 },
          { x: 0, y: 11, point: 13 },
          { x: 14, y: 11, point: 13 },
          { x: 1, y: 15, point: 13 },
          { x: 6, y: 16, point: 13 },
          { x: 11, y: 16, point: 13 },
          { x: 17, y: 16, point: 13 },
          { x: 12, y: 18, point: 13 },
          { x: 15, y: 18, point: 13 },
          { x: 19, y: 18, point: 13 },
          { x: 4, y: 19, point: 13 },
          { x: 1, y: 3, point: 12 },
          { x: 8, y: 4, point: 12 },
          { x: 4, y: 5, point: 12 },
          { x: 19, y: 5, point: 12 },
          { x: 16, y: 6, point: 12 },
          { x: 1, y: 8, point: 12 },
          { x: 13, y: 8, point: 12 },
          { x: 17, y: 8, point: 12 },
          { x: 6, y: 11, point: 12 },
          { x: 8, y: 11, point: 12 },
          { x: 18, y: 11, point: 12 },
          { x: 15, y: 12, point: 12 },
          { x: 16, y: 12, point: 12 },
          { x: 8, y: 15, point: 12 },
          { x: 0, y: 16, point: 12 },
          { x: 12, y: 16, point: 12 },
          { x: 0, y: 18, point: 12 },
          { x: 0, y: 19, point: 12 },
          { x: 1, y: 19, point: 12 },
          { x: 6, y: 19, point: 12 },
          { x: 9, y: 19, point: 12 },
          { x: 0, y: 0, point: 11 },
          { x: 17, y: 0, point: 11 },
          { x: 7, y: 1, point: 11 },
          { x: 11, y: 3, point: 11 },
          { x: 17, y: 3, point: 11 },
          { x: 16, y: 4, point: 11 },
          { x: 3, y: 5, point: 11 },
          { x: 11, y: 6, point: 11 },
          { x: 19, y: 6, point: 11 },
          { x: 7, y: 7, point: 11 },
          { x: 8, y: 7, point: 11 },
          { x: 11, y: 7, point: 11 },
          { x: 3, y: 8, point: 11 },
          { x: 7, y: 8, point: 11 },
          { x: 19, y: 8, point: 11 },
          { x: 15, y: 10, point: 11 },
          { x: 7, y: 11, point: 11 },
          { x: 11, y: 11, point: 11 },
          { x: 17, y: 12, point: 11 },
          { x: 8, y: 13, point: 11 },
          { x: 6, y: 15, point: 11 },
          { x: 14, y: 15, point: 11 },
          { x: 16, y: 15, point: 11 },
          { x: 3, y: 16, point: 11 },
          { x: 3, y: 0, point: 10 },
          { x: 19, y: 2, point: 10 },
          { x: 4, y: 3, point: 10 },
          { x: 6, y: 3, point: 10 },
          { x: 0, y: 5, point: 10 },
          { x: 15, y: 5, point: 10 },
          { x: 0, y: 7, point: 10 },
          { x: 3, y: 7, point: 10 },
          { x: 15, y: 7, point: 10 },
          { x: 4, y: 9, point: 10 },
          { x: 15, y: 9, point: 10 },
          { x: 19, y: 9, point: 10 },
          { x: 16, y: 10, point: 10 },
          { x: 19, y: 10, point: 10 },
          { x: 9, y: 11, point: 10 },
          { x: 13, y: 11, point: 10 },
          { x: 7, y: 15, point: 10 },
          { x: 1, y: 16, point: 10 },
          { x: 13, y: 19, point: 10 },
          { x: 12, y: 0, point: 9 },
          { x: 10, y: 4, point: 9 },
          { x: 0, y: 8, point: 9 },
          { x: 6, y: 8, point: 9 },
          { x: 12, y: 8, point: 9 },
          { x: 3, y: 9, point: 9 },
          { x: 0, y: 10, point: 9 },
          { x: 1, y: 11, point: 9 },
          { x: 0, y: 12, point: 9 },
          { x: 2, y: 12, point: 9 },
          { x: 3, y: 12, point: 9 },
          { x: 15, y: 14, point: 9 },
          { x: 2, y: 16, point: 9 },
          { x: 16, y: 16, point: 9 },
          { x: 8, y: 17, point: 9 },
          { x: 11, y: 17, point: 9 },
          { x: 8, y: 18, point: 9 },
          { x: 5, y: 19, point: 9 },
          { x: 18, y: 0, point: 8 },
          { x: 3, y: 3, point: 8 },
          { x: 13, y: 4, point: 8 },
          { x: 17, y: 4, point: 8 },
          { x: 16, y: 8, point: 8 },
          { x: 17, y: 11, point: 8 },
          { x: 19, y: 11, point: 8 },
          { x: 7, y: 12, point: 8 },
          { x: 11, y: 12, point: 8 },
          { x: 0, y: 13, point: 8 },
          { x: 3, y: 13, point: 8 },
          { x: 16, y: 13, point: 8 },
          { x: 11, y: 14, point: 8 },
          { x: 3, y: 15, point: 8 },
          { x: 19, y: 15, point: 8 },
          { x: 19, y: 16, point: 8 },
          { x: 7, y: 17, point: 8 },
          { x: 3, y: 18, point: 8 },
          { x: 4, y: 18, point: 8 },
          { x: 7, y: 18, point: 8 },
          { x: 19, y: 19, point: 8 },
          { x: 15, y: 0, point: 7 },
          { x: 0, y: 3, point: 7 },
          { x: 13, y: 3, point: 7 },
          { x: 5, y: 4, point: 7 },
          { x: 18, y: 7, point: 7 },
          { x: 3, y: 10, point: 7 },
          { x: 8, y: 10, point: 7 },
          { x: 6, y: 12, point: 7 },
          { x: 7, y: 13, point: 7 },
          { x: 12, y: 14, point: 7 },
          { x: 5, y: 15, point: 7 },
          { x: 17, y: 15, point: 7 },
          { x: 18, y: 15, point: 7 },
          { x: 7, y: 16, point: 7 },
          { x: 13, y: 16, point: 7 },
          { x: 4, y: 17, point: 7 },
          { x: 8, y: 19, point: 7 },
          { x: 12, y: 19, point: 7 },
          { x: 12, y: 1, point: 6 },
          { x: 8, y: 3, point: 6 },
          { x: 14, y: 3, point: 6 },
          { x: 4, y: 4, point: 6 },
          { x: 7, y: 5, point: 6 },
          { x: 4, y: 6, point: 6 },
          { x: 8, y: 6, point: 6 },
          { x: 0, y: 9, point: 6 },
          { x: 10, y: 11, point: 6 },
          { x: 1, y: 12, point: 6 },
          { x: 4, y: 13, point: 6 },
          { x: 19, y: 13, point: 6 },
          { x: 8, y: 14, point: 6 },
          { x: 15, y: 15, point: 6 },
          { x: 10, y: 16, point: 6 },
          { x: 14, y: 16, point: 6 },
          { x: 18, y: 16, point: 6 },
          { x: 0, y: 17, point: 6 },
          { x: 16, y: 0, point: 5 },
          { x: 15, y: 4, point: 5 },
          { x: 13, y: 7, point: 5 },
          { x: 2, y: 8, point: 5 },
          { x: 4, y: 8, point: 5 },
          { x: 2, y: 11, point: 5 },
          { x: 12, y: 12, point: 5 },
          { x: 14, y: 12, point: 5 },
          { x: 4, y: 14, point: 5 },
          { x: 9, y: 16, point: 5 },
          { x: 11, y: 18, point: 5 },
          { x: 10, y: 19, point: 5 },
          { x: 15, y: 19, point: 5 },
          { x: 16, y: 19, point: 5 },
          { x: 2, y: 0, point: 4 },
          { x: 8, y: 0, point: 4 },
          { x: 10, y: 0, point: 4 },
          { x: 15, y: 2, point: 4 },
          { x: 9, y: 3, point: 4 },
          { x: 10, y: 3, point: 4 },
          { x: 12, y: 4, point: 4 },
          { x: 19, y: 4, point: 4 },
          { x: 12, y: 6, point: 4 },
          { x: 4, y: 7, point: 4 },
          { x: 10, y: 7, point: 4 },
          { x: 8, y: 12, point: 4 },
          { x: 12, y: 13, point: 4 },
          { x: 3, y: 14, point: 4 },
          { x: 7, y: 14, point: 4 },
          { x: 9, y: 15, point: 4 },
          { x: 16, y: 17, point: 4 },
          { x: 7, y: 0, point: 3 },
          { x: 15, y: 1, point: 3 },
          { x: 19, y: 1, point: 3 },
          { x: 7, y: 2, point: 3 },
          { x: 12, y: 2, point: 3 },
          { x: 5, y: 3, point: 3 },
          { x: 0, y: 4, point: 3 },
          { x: 6, y: 4, point: 3 },
          { x: 3, y: 6, point: 3 },
          { x: 7, y: 6, point: 3 },
          { x: 11, y: 8, point: 3 },
          { x: 7, y: 9, point: 3 },
          { x: 16, y: 9, point: 3 },
          { x: 4, y: 11, point: 3 },
          { x: 0, y: 15, point: 3 },
          { x: 2, y: 15, point: 3 },
          { x: 15, y: 16, point: 3 },
          { x: 11, y: 19, point: 3 },
          { x: 5, y: 0, point: 2 },
          { x: 3, y: 1, point: 2 },
          { x: 4, y: 2, point: 2 },
          { x: 8, y: 5, point: 2 },
          { x: 12, y: 5, point: 2 },
          { x: 16, y: 5, point: 2 },
          { x: 5, y: 8, point: 2 },
          { x: 8, y: 8, point: 2 },
          { x: 9, y: 8, point: 2 },
          { x: 10, y: 8, point: 2 },
          { x: 5, y: 12, point: 2 },
          { x: 19, y: 12, point: 2 },
          { x: 4, y: 15, point: 2 },
          { x: 8, y: 16, point: 2 },
          { x: 15, y: 17, point: 2 },
          { x: 7, y: 19, point: 2 },
          { x: 14, y: 19, point: 2 },
          { x: 16, y: 1, point: 1 },
          { x: 3, y: 2, point: 1 },
          { x: 8, y: 2, point: 1 },
          { x: 15, y: 3, point: 1 },
          { x: 2, y: 4, point: 1 },
          { x: 11, y: 4, point: 1 },
          { x: 14, y: 4, point: 1 },
          { x: 5, y: 7, point: 1 },
          { x: 12, y: 7, point: 1 },
          { x: 16, y: 7, point: 1 },
          { x: 11, y: 9, point: 1 },
          { x: 4, y: 10, point: 1 },
          { x: 11, y: 10, point: 1 },
          { x: 12, y: 10, point: 1 },
          { x: 12, y: 11, point: 1 },
          { x: 16, y: 11, point: 1 },
          { x: 13, y: 12, point: 1 },
          { x: 0, y: 14, point: 1 },
          { x: 19, y: 14, point: 1 },
          { x: 12, y: 15, point: 1 },
          { x: 2, y: 19, point: 1 },
          { x: 1, y: 1, point: -16 },
          { x: 2, y: 1, point: -16 },
          { x: 5, y: 1, point: -16 },
          { x: 6, y: 1, point: -16 },
          { x: 9, y: 1, point: -16 },
          { x: 10, y: 1, point: -16 },
          { x: 13, y: 1, point: -16 },
          { x: 14, y: 1, point: -16 },
          { x: 17, y: 1, point: -16 },
          { x: 18, y: 1, point: -16 },
          { x: 1, y: 2, point: -16 },
          { x: 2, y: 2, point: -16 },
          { x: 5, y: 2, point: -16 },
          { x: 6, y: 2, point: -16 },
          { x: 9, y: 2, point: -16 },
          { x: 10, y: 2, point: -16 },
          { x: 13, y: 2, point: -16 },
          { x: 14, y: 2, point: -16 },
          { x: 17, y: 2, point: -16 },
          { x: 18, y: 2, point: -16 },
          { x: 1, y: 5, point: -16 },
          { x: 2, y: 5, point: -16 },
          { x: 5, y: 5, point: -16 },
          { x: 6, y: 5, point: -16 },
          { x: 9, y: 5, point: -16 },
          { x: 10, y: 5, point: -16 },
          { x: 13, y: 5, point: -16 },
          { x: 14, y: 5, point: -16 },
          { x: 17, y: 5, point: -16 },
          { x: 18, y: 5, point: -16 },
          { x: 1, y: 6, point: -16 },
          { x: 2, y: 6, point: -16 },
          { x: 5, y: 6, point: -16 },
          { x: 6, y: 6, point: -16 },
          { x: 9, y: 6, point: -16 },
          { x: 10, y: 6, point: -16 },
          { x: 13, y: 6, point: -16 },
          { x: 14, y: 6, point: -16 },
          { x: 17, y: 6, point: -16 },
          { x: 18, y: 6, point: -16 },
          { x: 1, y: 9, point: -16 },
          { x: 2, y: 9, point: -16 },
          { x: 5, y: 9, point: -16 },
          { x: 6, y: 9, point: -16 },
          { x: 9, y: 9, point: -16 },
          { x: 10, y: 9, point: -16 },
          { x: 13, y: 9, point: -16 },
          { x: 14, y: 9, point: -16 },
          { x: 17, y: 9, point: -16 },
          { x: 18, y: 9, point: -16 },
          { x: 1, y: 10, point: -16 },
          { x: 2, y: 10, point: -16 },
          { x: 5, y: 10, point: -16 },
          { x: 6, y: 10, point: -16 },
          { x: 9, y: 10, point: -16 },
          { x: 10, y: 10, point: -16 },
          { x: 13, y: 10, point: -16 },
          { x: 14, y: 10, point: -16 },
          { x: 17, y: 10, point: -16 },
          { x: 18, y: 10, point: -16 },
          { x: 1, y: 13, point: -16 },
          { x: 2, y: 13, point: -16 },
          { x: 5, y: 13, point: -16 },
          { x: 6, y: 13, point: -16 },
          { x: 9, y: 13, point: -16 },
          { x: 10, y: 13, point: -16 },
          { x: 13, y: 13, point: -16 },
          { x: 14, y: 13, point: -16 },
          { x: 17, y: 13, point: -16 },
          { x: 18, y: 13, point: -16 },
          { x: 1, y: 14, point: -16 },
          { x: 2, y: 14, point: -16 },
          { x: 5, y: 14, point: -16 },
          { x: 6, y: 14, point: -16 },
          { x: 9, y: 14, point: -16 },
          { x: 10, y: 14, point: -16 },
          { x: 13, y: 14, point: -16 },
          { x: 14, y: 14, point: -16 },
          { x: 17, y: 14, point: -16 },
          { x: 18, y: 14, point: -16 },
          { x: 1, y: 17, point: -16 },
          { x: 2, y: 17, point: -16 },
          { x: 5, y: 17, point: -16 },
          { x: 6, y: 17, point: -16 },
          { x: 9, y: 17, point: -16 },
          { x: 10, y: 17, point: -16 },
          { x: 13, y: 17, point: -16 },
          { x: 14, y: 17, point: -16 },
          { x: 17, y: 17, point: -16 },
          { x: 18, y: 17, point: -16 },
          { x: 1, y: 18, point: -16 },
          { x: 2, y: 18, point: -16 },
          { x: 5, y: 18, point: -16 },
          { x: 6, y: 18, point: -16 },
          { x: 9, y: 18, point: -16 },
          { x: 10, y: 18, point: -16 },
          { x: 13, y: 18, point: -16 },
          { x: 14, y: 18, point: -16 },
          { x: 17, y: 18, point: -16 },
          { x: 18, y: 18, point: -16 },
        ],
      },
      operationSec: 3,
      transitionSec: 1,
      nPlayer: 2,
      nAgent: 8,
      field: {
        width: 20,
        height: 20,
        points: [
          11, 15, 4, 10, 15, 2, 14, 3, 4, 15, 4, 15, 9, 16, 13, 7, 5, 11, 8, 16,
          14, -16, -16, 2, 14, -16, -16, 11, 16, -16, -16, 14, 6, -16, -16, 3,
          1, -16, -16, 3, 15, -16, -16, 1, 2, -16, -16, 3, 1, -16, -16, 14, 3,
          -16, -16, 4, 15, -16, -16, 10, 7, 12, 16, 8, 10, 3, 10, 15, 6, 4, 4,
          11, 16, 7, 6, 1, 14, 11, 16, 16, 3, 16, 1, 15, 6, 7, 3, 16, 12, 14, 9,
          1, 4, 8, 1, 5, 11, 8, 14, 4, 10, -16, -16, 11, 12, -16, -16, 6, 2,
          -16, -16, 14, 2, -16, -16, 10, 2, -16, -16, 12, 15, -16, -16, 3, 6,
          -16, -16, 3, 6, -16, -16, 11, 4, -16, -16, 16, 12, -16, -16, 11, 10,
          13, 15, 10, 4, 1, 16, 11, 11, 14, 4, 11, 1, 5, 16, 10, 1, 16, 7, 16,
          9, 12, 5, 11, 5, 2, 9, 11, 2, 2, 2, 3, 9, 12, 14, 15, 8, 12, 15, 11,
          6, -16, -16, 9, 10, -16, -16, 3, 13, -16, -16, 1, 14, -16, -16, 10, 3,
          -16, -16, 10, 9, -16, -16, 7, 1, -16, -16, 15, 7, -16, -16, 1, 1, -16,
          -16, 11, 10, -16, -16, 10, 13, 9, 5, 15, 3, 14, 12, 11, 12, 10, 6, 11,
          1, 10, 13, 16, 1, 8, 12, 8, 9, 6, 9, 9, 14, 2, 7, 8, 4, 15, 15, 8, 5,
          1, 5, 12, 12, 11, 16, 2, 8, -16, -16, 8, 6, -16, -16, 7, 11, -16, -16,
          15, 4, -16, -16, 14, 8, -16, -16, 6, 1, -16, -16, 4, 5, -16, -16, 4,
          6, -16, -16, 8, 7, -16, -16, 9, 16, -16, -16, 1, 3, 13, 3, 8, 2, 7,
          11, 10, 12, 4, 16, 15, 1, 15, 11, 6, 11, 7, 7, 8, 12, 10, 9, 11, 14,
          14, 13, 7, 2, 5, 6, 13, 12, 7, 6, 3, 9, 13, 6, 8, 6, -16, -16, 15, 7,
          -16, -16, 8, 9, -16, -16, 9, 16, -16, -16, 2, 4, -16, -16, 14, 12,
          -16, -16, 8, 8, -16, -16, 8, 9, -16, -16, 5, 13, -16, -16, 13, 16,
          -16, -16, 13, 12, 12, 1, 14, 13, 9, 12, 2, 7, 12, 5, 3, 7, 10, 2, 5,
          5, 14, 16, 8,
        ],
        tiles: [
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 1, player: 1 },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
          { type: 0, player: null },
        ],
      },
      players: [
        {
          id: "ゲスト",
          spec: "",
          agents: [
            { x: -1, y: -1 },
            { x: -1, y: -1 },
            { x: -1, y: -1 },
            { x: -1, y: -1 },
            { x: -1, y: -1 },
            { x: -1, y: -1 },
            { x: -1, y: -1 },
            { x: -1, y: -1 },
          ],
          point: { areaPoint: 0, wallPoint: 0 },
          type: "guest",
        },
        {
          id: "a1",
          spec: "",
          agents: [
            { x: 10, y: 5 },
            { x: 12, y: 1 },
            { x: 5, y: 5 },
            { x: 15, y: 5 },
            { x: 12, y: 9 },
            { x: 16, y: 7 },
            { x: 1, y: 8 },
            { x: 16, y: 9 },
          ],
          point: { areaPoint: 0, wallPoint: 363 },
          type: "account",
        },
      ],
      status: "ended",
    },
  ],
  gamesNum: 6,
};
